name: Token Data Aggregation

on:
  schedule:
    # Run daily at 10:00 UTC
    - cron: "0 10 * * *"
  workflow_dispatch:
    # Allow manual triggering

jobs:
  aggregate-tokens:
    runs-on: ubuntu-latest
    env:
      COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
      ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
      VERCEL_DEPLOY_HOOK_URL: ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Create tokens directory
        run: mkdir -p tokens

      - name: Run token aggregator
        run: |
          set -eou pipefail && cd tokens && python ../coin_info_fetcher.py && cd ../;

      - name: Configure Git
        run: |
          git config --local user.email "token-fetcher[bot]@users.noreply.github.com"
          git config --local user.name "token-fetcher[bot]"

      - name: Commit and push if changed
        run: |
          git add tokens/
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: update token data $(date +'%Y-%m-%d')" && git push)

      - name: Wait for GitHub synchronization
        run: sleep 10s

      - name: Trigger Vercel Deployment
        run: |
          curl -X POST "$VERCEL_DEPLOY_HOOK_URL"
